### PR TITLE
Reformat with yapf

### PR DESCRIPTION
**Pull request by sandlerben**
In a follow-up pull request, I will update the repos CI checks to ensure that all code being merged into flask-base is formatted with yapf.

### CODE REVIEW

**Comment by sandlerben** [comment]
#53

**Comment by sandlerben** [comment]
I also added isort for import sorting. 

All formatting can be run with `python manage.py format` now.

**Comment by yoninachmany** [comment]
lgtm

**Comment by abhisuri97** [comment]
I know that venv is excluded via gitignore but does yapf recursively search through a virtualenv folder if it is in the same dir as flask base? In general I would like to be explicit about the folders we include rather than exclude if the above statement is true.

**Comment by sandlerben** [comment]
@abhisuri97 both commands recursively format, but the way I call the commands from `python manage.py format` excludes a directory called `env`. Should I try to make it ignore virtual environments of different names? It might just be best to make the virtualenv name an argument of the `format` command.

**Comment by sandlerben** [comment]
TBH I think it's easier if everyone names their virtualenv the same thing for now on.

**Comment by sandlerben** [comment]
Actually, I'm going to call both commands on all python files in the top-level and in the `app` subdirectory.

**Comment by sandlerben** [comment]
Abhi once I get your lgtm I'll merge

**Comment by abhisuri97** [comment]
lgtm

**Pull request merged**
