### PR TITLE
is_anonymous is not a function

### PR DESCRIPTION
**Pull request by npezolano**

### CODE REVIEW

**Comment by abhisuri97** [comment]
thanks for this 👍. lgtm.

**Comment by sandlerben** [comment]
It's actually a wrapped function (with the @property decorator). See https://github.com/maxcountryman/flask-login/blob/05b8f8602ee81f7d131607ab4757899883462ba6/flask_login/mixins.py#L32

Very minor, but I think we should revert this. I think it's better for all `is_xyz` functions to be called in a consistent way (through an explicit function call).

**Comment by abhisuri97** [comment]
@sandlerben its wrapped with the @property decorator, preventing it from actually being called as a function (per my knowledge of how @property works). Also calling as a function causes the app to throw a `TypeError: 'bool' object is not callable` error.

**Comment by sandlerben** [comment]
Oh, interesting! I wonder why this never caused crashes

**Comment by abhisuri97** [comment]
the addition of @property objects only came in with recent versions of flask_login. When i did the major update PR #106, i thought i converted all the `is_xyz()` calls to `is_xyz` but it looks like i missed a few.

**Pull request merged**
