### PR TITLE
Add Code of Conduct

### PR DESCRIPTION
**Pull request by rileynwong**

### CODE REVIEW

**Comment by abhisuri97** [comment]
lgtm. wait for a ok from an exec member and merge :)

**Comment by abhisuri97** [comment]
it might also be a good idea to include a small line in `README.md` referring to the conduct code.

**Comment by sandlerben** [comment]
ooh this is cool! lgtm

**Comment by abhisuri97** [comment]
@nancywong I added the reference to the code of conduct in README.md. Feel free to merge now.

**Comment by yoninachmany** [comment]
@nancywong reason why `CONDUCT.md` exists here rather than https://github.com/hack4impact/constitution repo?

**Comment by abhisuri97** [comment]
@yoninachmany this was discussed in #meta but basically `CONDUCT.md` refers to the set of rules, guidelines, and values for open source contributions and our values regarding contributions in general. (common across several open source projects).

**Comment by yoninachmany** [comment]
@abhisuri97 thanks for fast and clear answer - i honestly didn't follow entire #meta conversation. maybe this was discussed, but since not all projects will be created from `flask-base`, how do we ensure that information from `conduct.md` will be known in that project?

**Comment by abhisuri97** [comment]
Well first note that any future `flask-base` projects and soon-to-be `js-base` projects that are forked from the respective bases will (by the nature of forking) include `CONDUCT.md`. If anyone would like to retroactively add `CONDUCT.md` to our previous projects, then feel free to do so.

But for future projects, I think it would be advisable to include this `CONDUCT.md` (or any similar) file to be explicit about the nature of open-source contributions towards our projects, whether they are derived from any "base" or not.

**Pull request merged**
