### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by sandlerben**

### CODE REVIEW

**Comment by maxmcc** [comment]
We should be careful here. Significant portions of this code are adapted from Miguel Grinberg's [Flask book](http://flaskbook.com) and its [accompanying project](https://github.com/miguelgrinberg/flasky). I believe the code there is MIT-licensed as well, but he does retain copyright.

**Comment by sandlerben** [comment]
@maxmcc what do you propose we do?

**Comment by maxmcc** [comment]
We just need to abide by his license, specifically this part:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

This means:
- [x] licensing our derivative work under MIT, and including the MIT license with our code
- [ ] noting that he retains copyright over the portions of the code that he wrote

**Comment by sandlerben** [comment]
Max can we add inline comments of the stuff that was taken from his code?

**Comment by sandlerben** [comment]
@maxmcc Bump

**Comment by maxmcc** [comment]
That's honestly the best solution. It might be easiest to diff the code in his project against ours, and then function- or module-level comment the parts we used.

**Comment by sandlerben** [comment]
Don't we need to do that regardless of whether we add MIT to this project? Can I merge this PR and add that as an issue?

**Comment by maxmcc** [comment]
Yeah. I guess the thing to change for this PR is just modifying the line as follows:

``` diff
-Copyright (c) 2016 Hack4Impact
+Copyright (c) 2016 Hack4Impact. Portions adopted from code by Miguel Grinberg.
```

**Pull request merged**
