### PR TITLE
Added Dockerfile - for testing not production

### PR DESCRIPTION
**Pull request by MohammedRashad**
This is intended to help you run the template with little to no hassle.
A complete version using docker compose is being developed and will patch with it soon.

### CODE REVIEW

**Comment by abhisuri97** [comment]
Thanks for doing this. Could you also add changes to the readme for instructions on how to use the dockerfile and what variables to change for a custom deployment?

**Comment by MohammedRashad** [comment]
@abhisuri97 I added a simple description + the env. variables.
Let me know what do you think.

**Comment by abhisuri97** [comment]
This looks good to me. Let me know if you're fine with merging this as is or if you want to add in  other features before I merge.

**Comment by MohammedRashad** [comment]
I'm fine with this

**Pull request merged**
