### PR TITLE
Add analytics

### PR DESCRIPTION
**Pull request by katiejiang**
* Include Google analytics by setting environment variable `GOOGLE_ANALYTICS_ID`
* Include Segment analytics by setting environment variable `SEGMENT_API_KEY`
* Update documentation for analytics

### CODE REVIEW

**Comment by sandlerben** [comment]
amazing

**Comment by sandlerben** [comment]
would we consider using segment.com?

**Comment by katiejiang** [comment]
@sandlerben I can add an option for segment!

**Comment by katiejiang** [comment]
We can probably leave the decision of which analytics platform to our clients!

**Comment by sandlerben** [comment]
The nice thing about segment is it forwards the data to any analytics provider you want (google, mixpanel, etc)!

**Comment by katiejiang** [comment]
^This would be a great thing to include in our hand-off document actually

**Pull request merged**
