### PR TITLE
Commenting

### PR DESCRIPTION
**Pull request by abhisuri97**
# Commenting

Most, if not all, of the files have been commented with explanatory descriptions of all inner-workings of functions and packages that are not quite explained in the _Flask Web Development_ book. This will serve as a future reference for users. 

Example commenting
# Import Reordering

Wherever possible, all imports have been arranged in the following order: 
- System
- 3rd party
- Our code
  Within each of these categories, imports have been ordered alphabetically. 

If allowable, import statements from a single package have also been rearranged in alphabetical order. All imports have been tested to avoid circular imports. If an import could not be placed in a position conforming to PEP8 style, it was left in its place in the code to avoid major refactoring of some basic components.
Example Import
# Nav Refactoring

A long awaited change to navigation has occurred! Navigation items now default to the `render_menu_item` macro in `nav_macros.html` rather than relying upon hardcoded values. This opens the ability to have active state shown on the user end, vastly improving navigation across the application.
Navigation Now
Additionally Icons are a thing now! 

Lastly, in navigation refactoring, the ability to add a series of submenus has been finally added. 
The following code produces the dropdown scheme seen in the following images.

```
{% set dropdown = 
           [
              ('account stuff',
               [
                ('account.login', 'login', 'sign in'),
                ('account.logout', 'logout', 'sign out'),
                ('2nd drop', [
                  ('account.login', 'login 2', ''),
                  ('3rd drop', [
                    ('main.index', 'home 2', '')
                  ])
                ])
              ]
            ),
            ('main.index', 'home 1', 'home')
          ]
%}
{{ nav.render_nav(current_user, dropdown) }}
```

Desktop:
Submenus Desktop

Mobile Part 1:
Submenus Mobile

Mobile Part 2:
Submenus Mobile 2
# Small Updates:
- Force user to set secret key when mode is production or higher (throws `AssertionError` if not). 
- refactored `utils.py` methods. 
- changed index.html to reflected logged in vs logged out state. 
- added vim *.swp to .gitignore
- added zxcvbn(?) password checker to local scripts
- tiny editing of Bundle creation
- removal of Gulp references.

### CODE REVIEW

**Comment by sandlerben** [comment]
Are there any automatic formatters for python? I would strongly prefer that as a long-term solution.

**Comment by abhisuri97** [comment]
@ben to my knowledge there are not (and for a good reason since Blueprint is very sensitive about the position of its imports) and the possibility for circular imports is a thing haha (<- mainly a concern when dealing with our own code rather than 3rd party)

**Comment by sandlerben** [comment]
Actually found [this](https://pypi.python.org/pypi/autopep8), seems very promising.

**Comment by abhisuri97** [comment]
To formally respond to @sandlerben, the autopep8 formatter doesn't alphabetize or sort by import type (system, 3rd party, us).

**Comment by sandlerben** [comment]
Can you split this up into a few smaller PRs? Will make it much easier to review.

You can use `git cherry-pick` or `git checkout`.

**Comment by abhisuri97** [comment]
#49 #48 
This PR is a superset of the above PRs :)

**Comment by yoninachmany** [comment]
@abhisuri97 should u fix conflicts? also trying to understand how this branch gets maintained as flask-base changes

**Comment by yoninachmany** [comment]
@abhisuri97 status?

**Comment by abhisuri97** [comment]
Yeah I'm going to be making a version of this to be hosted in read the docs. Seems like the best solution. Keeps comments out of the code and is meant for more general explanation of the purpose of functions and how everything goes together.

**Comment by abhisuri97** [comment]
#88

**Pull request closed without merging**
