### PR TITLE
:shirt: Refactor blueprints

### PR DESCRIPTION
**Pull request by anselal**
Refactor imports and apply some PEP8

### CODE REVIEW

**Comment by anselal** [comment]
The error makes no sense

**Comment by abhisuri97** [comment]
Closing in favor of other one #161

**Comment by anselal** [comment]
Actually this one should be open and #161 should close. 
This one includes the changes from #161.
Sorry for that.

**Comment by anselal** [comment]
I will push more changes here

**Comment by anselal** [comment]
I am done refactoring for now !
You can check if this PR suits you

**Comment by abhisuri97** [comment]
merged

**Comment by anselal** [comment]
Great, thank you !!

**Comment by anselal** [comment]
I see here https://circleci.com/gh/hack4impact/flask-base/307 that there is an import error I cannot replicate.

**Comment by anselal** [comment]
I fixed this at #166

**Pull request merged**
