### PR TITLE
Ignore generated css/js files

### PR DESCRIPTION
**Pull request by ozbek**

### CODE REVIEW

**Comment by ozbek** [comment]
@sandlerben, @abhisuri97: can you guys take a look on this, please?

**Comment by abhisuri97** [comment]
Since flask-base is really optimized for heroku, we  don't want to completely ignore the generated css/js files

**Comment by ozbek** [comment]
Then, perhaps, those files need to be added/committed?

**Comment by ozbek** [comment]
Also, I am not sure how that effects heroku: it does not care whether a file is auto-generated (and not committed on source tree), does it?

**Comment by abhisuri97** [comment]
It only keeps track of files that are actually committed. if the file isn't committed, it'll be lost.

**Comment by ozbek** [comment]
Right. These three files are generated in [assets.py](https://github.com/hack4impact/flask-base/blob/931c8a9801c6a2f4d655d55eac20182b50a98ddc/app/assets.py), so they are already committed elsewhere in the source tree and does not need to be committed here also. 

Now that I took closer look on `assets.py`, I think [`app/static/styles/app.css`](https://github.com/hack4impact/flask-base/blob/931c8a9801c6a2f4d655d55eac20182b50a98ddc/app/static/styles/app.css) should also be added to gitignore. What do you think?

**Pull request closed without merging**
