### PR TITLE
:shirt: Refactor account blueprint

### PR DESCRIPTION
**Pull request by anselal**
Refactor imports and apply some PEP8

### CODE REVIEW

**Comment by anselal** [comment]
The error says "File views.py has 255 lines of code (exceeds 250 allowed). Consider refactoring. " but `app/account/views.py` has actually 292 lines of code.
Is this really necessary to limit the length of the file ???
I think you can safely merge this PR

**Comment by abhisuri97** [comment]
Requesting @sandlerben to review PR. Could we have some justification for the changes or is  it merely aesthetic for changing around blueprint instantiation a bit

**Comment by abhisuri97** [comment]
@anselal i removed the weird CodeClimate rule. you should be good to reopen this PR if that was your concern

**Comment by anselal** [comment]
Instantiating the Blueprint inside the `__init__.py` and importing the `views.py` inside the same file creates circular imports

**Comment by abhisuri97** [comment]
Reffing back to #162

**Comment by anselal** [comment]
> Instantiating the Blueprint inside the __init__.py and importing the views.py inside the same file creates circular imports

Does this makes sense ? Can I proceed ?

**Pull request closed without merging**
