### PR TITLE
changed to sendgrid

### PR DESCRIPTION
**Pull request by abhisuri97**
Should we reflect in the readme to create a sendgrid account?

### CODE REVIEW

**Comment by sandlerben** [comment]
would this work https://devcenter.heroku.com/articles/sendgrid

**Comment by abhisuri97** [comment]
@sandlerben So that heroku wrapper is just for the sendgrid api. this pr makes the edit so we can use sendgrid smtp and as a result do not have to change our `email.py` code. Either way is valid. Up to you regarding which one to do (changing to the api requires `email.py` to be edited though).

**Comment by sandlerben** [comment]
I _hate_ the flask-mail interface so I'm all for abandoning it

**Comment by sandlerben** [comment]
this looks good though, we can probably make that change later

**Comment by sandlerben** [comment]
abhi can you update README in follow-up

**Pull request merged**
