### PR TITLE
replaced forgery_py with fake-factory

### PR DESCRIPTION
**Pull request by aharelick**
r @sandlerben @jondubin 
I think we needed a new faking library, the one that was chosen wasn't that robust. If you're going by github stars, the replacement is very popular (https://github.com/joke2k/faker).

Docs: http://fake-factory.readthedocs.org/en/latest/index.html

### CODE REVIEW

**Comment by sandlerben** [comment]
r @maxmcc because he added forgery-py and might have thoughts

**Comment by sandlerben** [comment]
lgtm

**Comment by aharelick** [comment]
Max gave this the okay on slack

**Comment by sandlerben** [comment]
:+1:

**Pull request merged**
